---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: imagescans.shipwright.io
spec:
  group: shipwright.io 
  names:
    kind: ImageScan
    listKind: ImageScanList
    plural: imagescans
    singular: imagescan
  preserveUnknownFields: false
  scope: Cluster
  versions:
  - name: v1beta1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              failures:
                type: array
                nullable: true
                items:
                  type: object
                  properties:
                    when:
                      type: string
                    error:
                      type: string
              result:
                description: The image scan result
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
